name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

        
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli:  'latest'
          bb:   'latest'

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            ~/.npm
            .shadow-cljs
          key: cljdeps-${{ hashFiles('deps.edn') }}-${{ hashFiles ('package.json') }}-${{ hashFiles ('package-lock.json') }}
          restore-keys: cljdeps-

      - name: Fix git dubious directory ownership error
        run: git config --global --add safe.directory /__w/re-frame-test/re-frame-test

      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: 811961

      - run: bb test :chrome-path '"${{ steps.setup-chrome.outputs.chrome-path }}"'

      - name: Slack notification
        uses: homoluctus/slatify@v3.0.0
        if: failure() || cancelled()
        with:
          type: ${{ job.status }}
          job_name: re-frame-test Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
