name: cd
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    container:
      # Source: https://github.com/day8/dockerfile-for-dev-ci-image
      image: ghcr.io/day8/dockerfile-for-dev-ci-image/chrome-56:2
    steps:
      - uses: actions/checkout@v1
      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('project.clj') }}-${{ hashFiles('**/deps.cljs') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: shadow-cljs compiler cache
        uses: actions/cache@v4
        with:
          path: .shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-
      - run: lein ci 
      - name: Slack notification
        uses: homoluctus/slatify@v3.0.0
        if: failure() || cancelled()
        with:
          type: ${{ job.status }}
          job_name: re-frame-test Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    needs: test
    runs-on: ubuntu-20.04
    container:
      # Source: https://github.com/day8/dockerfile-for-dev-ci-image
      image: ghcr.io/day8/dockerfile-for-dev-ci-image/chrome-56:2
    steps:
      - uses: actions/checkout@v1
      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run lein release
        run: |
          CLOJARS_USERNAME=${{ secrets.CLOJARS_USERNAME }} CLOJARS_TOKEN=${{ secrets.CLOJARS_TOKEN }} GITHUB_USERNAME=${{ github.actor }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} lein release
      # This creates a 'GitHub Release' from the tag and includes link to the CHANGELOG
      # at that point in the Git history. We do not use draft or prerelease features as
      # we always want the latest release to show in the right hand column of the project
      # page regardless of if it is a stable release.
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            [Changelog](https://github.com/day8/re-frame-test/blob/${{ github.ref }}/CHANGELOG.md)
          draft: false
          prerelease: false
      - name: Slack notification
        uses: homoluctus/slatify@v3.0.0
        if: always()
        with:
          type: ${{ job.status }}
          job_name: re-frame-test Deployment
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
