name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      # Source: https://github.com/day8/dockerfile-for-dev-ci-image
      image: ghcr.io/day8/dockerfile-for-dev-ci-image/chrome-56:2
    steps:
      - uses: actions/checkout@v5
      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('project.clj') }}-${{ hashFiles('**/deps.cljs') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: shadow-cljs compiler cache
        uses: actions/cache@v4
        with:
          path: .shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-
      - run: lein ci 
      - name: Slack notification
        uses: homoluctus/slatify@v3.0.0
        if: failure() || cancelled()
        with:
          type: ${{ job.status }}
          job_name: re-frame-test Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
